pipeline:
  build:
    image: golang
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - export GOPATH=/drone
      - mkdir /drone/bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      # - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go build
      # - go test

