pipeline:
  build:
    image: golang
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - export GOPATH=/drone
      - dep ensure
      - go build
      - go test

