pipeline:
  build:
    image: golang
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - export GOPATH=/drone
      - echo $PWD
      - echo $GOPATH
      # - go get -u github.com/golang/dep/cmd/dep
      # - dep ensur
      - go build
      # - go test

